# -*- coding: utf-8 -*-
"""Extra per-service detail content. Keyed by service slug.
Merged into SERVICES entries in build.py to render the
'What's included / How long / How pricing works' detail section."""

SERVICE_EXTRAS = {
    "lube-oil-filter": {
        "included": [
            "Fresh oil matched to your manufacturer specification, synthetic or conventional",
            "New quality oil filter, installed and torqued to spec",
            "Chassis lubrication where your vehicle has grease points",
            "Fluid top ups: washer, coolant and power steering as needed",
            "Free multi point courtesy inspection with a written summary",
            "Maintenance light reset and a reminder sticker for your windshield",
        ],
        "duration": "About 30 to 45 minutes, including the free inspection. Walk ins welcome.",
        "price_note": "Priced by oil type and engine size. We confirm the exact price before we start, and the quote always includes the filter, the inspection and shop supplies with no hidden extras.",
    },
    "diagnostic-services": {
        "included": [
            "Full computer scan of every module, not just the engine computer",
            "Stored, pending and history codes with freeze frame data recorded",
            "Live sensor data analysis while the fault is reproduced",
            "Hands on inspection of wiring, connectors and mechanical parts",
            "Written report of the confirmed fault and the repair options",
            "Upfront written quote for the repair, approved by you first",
        ],
        "duration": "Most diagnostics take 1 to 2 hours. Complex intermittent faults can take longer, and we will tell you before the meter keeps running.",
        "price_note": "A flat diagnostic fee covers the technician time to find the fault. If you approve the repair with us, the diagnostic fee is applied toward the repair cost.",
    },
    "electrical-diagnostic": {
        "included": [
            "Wiring diagram research for your exact year, make and model",
            "Voltage, resistance and voltage drop testing on the suspect circuits",
            "Ground and connector inspection, cleaning and repair",
            "Parasitic drain testing with the vehicle fully asleep",
            "Repair of the failed wire, terminal or component, not just parts swapping",
            "Full circuit retest under load to prove the fix",
        ],
        "duration": "Simple faults take 1 to 2 hours. Intermittent electrical issues and parasitic drains can take a half day of methodical testing.",
        "price_note": "Quoted by diagnostic time plus the actual repair. Many electrical faults are fixed with a proper wire or terminal repair, which costs far less than replacing a module.",
    },
    "fuel-filter-replacement": {
        "included": [
            "Safe fuel pressure relief before any connection is opened",
            "New quality fuel filter with fresh seals and proper line connections",
            "Inspection of fuel lines, clamps and fittings for rust and leaks",
            "Fuel pressure test after installation to confirm spec",
            "Road test to confirm smooth acceleration under load",
        ],
        "duration": "Usually 1 to 2 hours, depending on whether the filter is inline under the car or inside the tank with the pump.",
        "price_note": "Inline filters are an affordable service. Tank mounted filters cost more because the tank must be accessed. We confirm which type your car has and quote it in writing first.",
    },
    "preventative-maintenance": {
        "included": [
            "Factory scheduled service items for your mileage milestone",
            "Engine oil, filter and all fluid level checks and top ups",
            "Brake pad and rotor measurement with the numbers in writing",
            "Tire tread depth, pressure check and rotation where applicable",
            "Belt, hose, battery and light inspection",
            "Written report prioritized by safety so you can plan ahead",
        ],
        "duration": "Most milestone services take 1 to 2 hours. Larger intervals with spark plugs or fluids can take half a day.",
        "price_note": "Priced from your manufacturer schedule, not a generic package. You see every line item and approve the list before we begin, and we never add services you did not ask for.",
    },
    "brake-replacement-repair": {
        "included": [
            "Pad and rotor thickness measured with the numbers shown to you",
            "Caliper, slide pin and brake hose inspection",
            "Quality pads and rotors matched to your vehicle",
            "Hardware cleaned or replaced, calipers serviced",
            "Brake fluid condition check",
            "Proper bedding procedure and a road test on every brake job",
        ],
        "duration": "A standard pad and rotor service takes 2 to 3 hours. Caliper or brake line work can extend the visit.",
        "price_note": "Priced per axle with parts and labour broken out in writing. Rotor condition decides whether resurfacing or replacement is the honest call, and we show you the measurements.",
    },
    "engine-repair-maintenance": {
        "included": [
            "Full diagnosis with scan data, compression or leak down testing where needed",
            "Gaskets, seals, belts and tune up components as diagnosed",
            "Quality parts that meet or exceed manufacturer specifications",
            "Torque specs followed on every fastener",
            "Fluids topped up and leaks rechecked after repair",
            "Road test and recheck before the car leaves",
        ],
        "duration": "Tune ups take a few hours. Gasket and seal work ranges from half a day to multiple days depending on the engine. We give you a realistic timeline with the quote.",
        "price_note": "Every engine job starts with diagnosis and a written quote. Complex work is quoted with parts and labour separate, and we call before doing anything beyond the approved scope.",
    },
    "coolant-flush": {
        "included": [
            "Complete drain of old coolant from radiator, block and heater core",
            "System flush to remove scale and deposits",
            "Fresh antifreeze mixed for Canadian winter protection",
            "Thermostat, hoses and water pump area inspection",
            "Pressure test of the full cooling system",
            "Bleeding of air pockets and a heat output check",
        ],
        "duration": "About 1.5 to 2 hours, including the pressure test and proper bleeding.",
        "price_note": "A flat service price for most vehicles, confirmed before we start. If the pressure test finds a leak, we quote that repair separately and you decide.",
    },
    "ball-joint-replacement": {
        "included": [
            "Suspension inspection to confirm the ball joint is the true cause of the noise",
            "Quality ball joint or complete control arm assembly as appropriate",
            "Proper torque specs on every fastener",
            "Related bushings and hardware inspected while apart",
            "Wheel alignment check recommended and quoted separately",
            "Road test over bumps and through turns to verify the fix",
        ],
        "duration": "Usually 2 to 3 hours per side. Control arm assemblies can be quicker than pressing in individual joints.",
        "price_note": "Quoted per side with parts and labour separate. If an alignment is needed after the work, it is quoted as its own line so you see the full picture.",
    },
    "fuel-pump-replacement": {
        "included": [
            "Fuel pressure and volume testing before condemning the pump",
            "Electrical testing of the pump circuit, relay and wiring",
            "Quality replacement pump, with the tank strainer where applicable",
            "Tank and lock ring inspection while open",
            "Fuel pressure verification after installation",
            "Road test including sustained highway speed",
        ],
        "duration": "Typically 2 to 4 hours. Some vehicles need the tank dropped, others have an access panel that speeds the job.",
        "price_note": "We prove the pump is the problem with pressure testing first, so you never pay for a pump you did not need. The written quote covers the pump, related parts and labour.",
    },
    "ac-service-replacement": {
        "included": [
            "System pressure readings and performance test",
            "Electronic leak detection and dye testing where needed",
            "Proper refrigerant recovery, never vented to the air",
            "Recharge to the exact factory specification by weight",
            "Compressor, condenser, dryer and line inspection",
            "Cabin vent temperature verified after service",
        ],
        "duration": "A recharge with leak testing takes 1 to 2 hours. Compressor or component replacement takes longer and is quoted separately.",
        "price_note": "Recharge and leak testing are quoted upfront. If a component has failed, you get a separate written quote for the part and labour before we proceed.",
    },
    "wheel-bearings-replacement": {
        "included": [
            "Road test and stethoscope diagnosis to confirm which bearing is noisy",
            "Quality hub assembly or bearing, pressed in with proper tools",
            "ABS sensor and tone ring inspection where integrated",
            "Torque specs followed on the axle nut and hub bolts",
            "Brake components rechecked during reassembly",
            "Road test to confirm the humming is gone",
        ],
        "duration": "Usually 1.5 to 2.5 hours per wheel, depending on whether it is a bolt on hub or a pressed bearing.",
        "price_note": "Quoted per wheel. We diagnose the exact noisy corner first, so you only replace the bearing that has actually failed.",
    },
    "strut-assembly-replacement": {
        "included": [
            "Bounce and road test diagnosis plus a visual check for leaks and wear",
            "Quality struts, shocks or complete quick strut assemblies",
            "Mounts, bearings and boots replaced with the assembly where worn",
            "Proper torque on all suspension fasteners",
            "Wheel alignment check recommended after replacement",
            "Road test for handling, noise and ride comfort",
        ],
        "duration": "Usually 2 to 3 hours per axle. Quick strut assemblies are faster than rebuilding individual struts.",
        "price_note": "Quoted per axle with parts and labour broken out. An alignment after strut work is quoted as a separate line so the total is clear.",
    },
    "oxygen-sensor-replacement": {
        "included": [
            "Scan and live data to confirm the sensor is the cause, not a symptom",
            "Exhaust and wiring inspection for the real root cause",
            "Quality oxygen sensor matched to your vehicle",
            "Proper torque and anti seize on the threads",
            "Code clear and drive cycle verification",
            "Fuel trim readings rechecked to confirm the fix",
        ],
        "duration": "Usually 1 to 1.5 hours. Sensors seized in the exhaust can take longer, and we will tell you if that happens.",
        "price_note": "We verify the sensor is actually failed before replacing it, because O2 codes are often caused by exhaust leaks or fuel issues. You pay for the fix, not a guess.",
    },
    "battery-alternator-starter": {
        "included": [
            "Battery load test and state of health report",
            "Alternator output test under electrical load",
            "Starter draw test and cranking voltage check",
            "Cable, terminal and ground inspection and cleaning",
            "Parasitic drain test if the battery keeps dying",
            "Written summary of which component failed and why",
        ],
        "duration": "A full starting and charging system test takes about 45 minutes to 1 hour. Drain testing can add time.",
        "price_note": "Testing is quoted upfront and you only replace the component that failed the test. Terminal cleaning and cable service are often all a car needs.",
    },
    "cv-axle-shaft-assembly": {
        "included": [
            "Road test and turn test to confirm which axle is clicking",
            "Boot inspection for tears and grease loss",
            "Quality complete CV axle assembly",
            "Transmission seal inspection while the axle is out",
            "Proper torque on the axle nut and suspension fasteners",
            "Road test with sharp turns to verify the clicking is gone",
        ],
        "duration": "Usually 1.5 to 2.5 hours per side.",
        "price_note": "Quoted per side with parts and labour separate. We replace the complete assembly rather than rebooting a worn joint, because it lasts longer and costs less in labour.",
    },
    "ignition-coils-spark-plugs": {
        "included": [
            "Misfire diagnosis to identify the exact failing cylinder",
            "Coil and plug testing before any parts are ordered",
            "Quality spark plugs gapped to factory specification",
            "Coil replacement only on the cylinders that need it, unless the set is aged",
            "Intake and vacuum leak check where relevant",
            "Road test and misfire monitor recheck",
        ],
        "duration": "Usually 1 to 2 hours. Some engines need intake removal to reach the rear plugs, which adds time and is quoted upfront.",
        "price_note": "We test first and replace what failed. If all coils are the same age and one has failed, we will tell you honestly whether replacing the set now saves a second visit.",
    },
    "engine-transmission-mount": {
        "included": [
            "Diagnosis of the clunk with the car on the lift and under load",
            "Inspection of all mounts, not just the obvious one",
            "Quality replacement mounts matched to your vehicle",
            "Proper torque specs and alignment of the powertrain",
            "Related bushings and brackets checked while accessible",
            "Road test through drive, reverse and idle to verify smoothness",
        ],
        "duration": "Usually 2 to 4 hours depending on how many mounts are worn and how buried they are.",
        "price_note": "Quoted after we identify which mounts have failed. Replacing mounts as a matched set is quoted as an option when the rest are close behind.",
    },
    "collision-body-work": {
        "included": [
            "Full damage assessment with photos and measurements",
            "Written estimate broken out by panel, parts and labour",
            "Dent removal, panel repair or replacement as appropriate",
            "Panel gaps and alignment checked against factory lines",
            "Corrosion protection on repaired panels",
            "Final wash and walk around inspection with you",
        ],
        "duration": "Minor dents take a day or two. Panel replacement and multi panel repairs take several days. We give you a realistic completion date with the estimate.",
        "price_note": "Written estimates before any work begins. We work with insurance claims and can explain the estimate line by line. You approve everything first.",
    },
    "frame-straightening": {
        "included": [
            "Computerized frame measurement against factory specifications",
            "Written report showing every point that is out of spec",
            "Hydraulic straightening on the frame bench",
            "Re-measurement to confirm the frame is back within tolerance",
            "Suspension mounting point verification",
            "Alignment check recommended after straightening",
        ],
        "duration": "Measurement and assessment take a few hours. Straightening time depends on the severity and is quoted after measurement.",
        "price_note": "Measurement comes first and is quoted separately, so you know exactly what is bent before committing to the straightening work.",
    },
    "auto-painting": {
        "included": [
            "Panel preparation: sanding, filling and priming",
            "Computerized colour matching to your factory paint code",
            "Professional spray booth application",
            "Clear coat for depth, gloss and UV protection",
            "Curing time respected before polishing",
            "Final polish and inspection under proper lighting",
        ],
        "duration": "Single panels take 2 to 3 days including prep and cure time. Full resprays take a week or more. Rushing paint is how orange peel happens, so we do not rush.",
        "price_note": "Quoted per panel or for the full vehicle after seeing the car. Prep work is where the quality lives, and the quote shows it as its own line.",
    },
    "towing-service": {
        "included": [
            "24/7 dispatch, day, night, weekends and holidays",
            "Flatbed and wheel lift trucks for cars, SUVs and light trucks",
            "Careful loading with proper tie downs, no drag damage",
            "Transport to our shop or the destination you choose",
            "Accident scene response coordinated with you",
            "Direct handoff to our service team if the car needs repair",
        ],
        "duration": "We dispatch immediately when you call. Arrival time depends on your location and traffic, and we will give you an honest estimate on the phone.",
        "price_note": "Quoted by distance before the truck rolls, so there are no surprises. If we tow your car to our shop and you approve the repair, we will talk about the tow on the final bill.",
    },
}
