# -*- coding: utf-8 -*-
"""Content data for the Apex Collision Center static site."""

SITE = {
    "name": "Apex Collision Center",
    "short": "Apex",
    "domain": "apexcollisioncenter.ca",
    "url": "https://apexcollisioncenter.ca",
    "phone_display": "(416) 661-6665",
    "phone_href": "+14166616665",
    "email": "mustafa@apexcollisioncenter.ca",
    "street": "Unit 41 & 42, 4544 Dufferin Street",
    "city": "Toronto",
    "district": "York University Heights, North York",
    "province": "ON",
    "postal": "M3H 5X2",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Apex+Collision+Center+4544+Dufferin+Street+North+York",
    "tagline": "Complete car care in North York, done right the first time.",
    "description": "Apex Collision Center is a full service auto repair and body shop at Unit 41 & 42, 4544 Dufferin Street in Toronto (York University Heights, North York), Ontario. We handle oil changes, brakes, diagnostics, electrical, AC, suspension, engine work, collision body repair, frame straightening, auto painting and 24/7 towing for all makes and models.",
}

HOURS = [
    {"day": "Monday", "time": "9:00 AM - 5:00 PM", "dow": 1},
    {"day": "Tuesday", "time": "9:00 AM - 5:00 PM", "dow": 2},
    {"day": "Wednesday", "time": "9:00 AM - 5:00 PM", "dow": 3},
    {"day": "Thursday", "time": "9:00 AM - 5:00 PM", "dow": 4},
    {"day": "Friday", "time": "9:00 AM - 5:00 PM", "dow": 5},
    {"day": "Saturday", "time": "10:00 AM - 3:00 PM", "dow": 6},
    {"day": "Sunday", "time": "Closed", "dow": 0},
]

SERVICES = [
    {
        "slug": "lube-oil-filter",
        "name": "Lube, Oil and Filter",
        "tagline": "Clean oil on schedule keeps your engine alive.",
        "img": "oil-change.jpg",
        "card": "Full service oil changes with quality oil and a new filter, plus a courtesy inspection at every visit.",
        "intro": [
            "Engine oil is the lifeblood of your car. It lubricates moving parts, carries heat away from hot spots, and traps dirt before it can cause wear. Over time oil breaks down and the filter fills up, which is why regular changes are the single cheapest way to protect your engine.",
            "At Apex Collision Center every oil service includes fresh quality oil matched to your manufacturer spec, a new oil filter, and a free multi point check of fluids, belts, lights and tire condition. You drive out knowing exactly where your car stands.",
        ],
        "signs": [
            "Oil change sticker mileage has passed, or it has been more than 6 months",
            "Dashboard oil light or maintenance reminder is on",
            "Oil on the dipstick looks dark, gritty or low",
            "Engine sounds louder or rougher than usual",
            "You notice a burning oil smell after driving",
        ],
        "steps": [
            ("Drain and inspect", "We drain the old oil completely and check it for metal particles or coolant traces that can warn of bigger problems."),
            ("New filter, fresh oil", "A new quality filter goes on, then fresh oil that meets your vehicle maker specification, filled to the exact level."),
            ("Lube and check", "We lubricate chassis points where applicable and top up washer fluid, coolant and power steering fluid."),
            ("Courtesy inspection", "Belts, hoses, lights, wipers, tire tread and brake pad thickness get a quick visual check, free with every oil change."),
            ("Reset and remind", "We reset your maintenance light and place a reminder sticker so you always know when the next service is due."),
        ],
        "faqs": [
            ("How often should I change my oil?", "Most modern cars need an oil change every 8,000 to 12,000 km or every 6 to 12 months, depending on the oil type and how you drive. Your owner manual has the exact interval. We set a reminder sticker so you never have to guess."),
            ("Synthetic or conventional oil?", "We follow your manufacturer specification. Most newer vehicles call for synthetic or synthetic blend oil because it resists breakdown far longer. We will explain the options and the price difference before we start."),
            ("How long does an oil change take?", "A standard oil change takes about 30 to 45 minutes, including the free multi point inspection. You can wait in our lounge or drop the car and come back."),
        ],
    },
    {
        "slug": "diagnostic-services",
        "name": "Diagnostic Services",
        "tagline": "We find the real problem before we touch a wrench.",
        "img": "diagnostics.jpg",
        "card": "Computer diagnostics and hands on testing that pinpoint warning lights, strange noises and performance issues.",
        "intro": [
            "Modern cars have dozens of computers watching every system. When the check engine light comes on, the car stores a code, but the code is only a starting point. A proper diagnosis connects the code to live sensor data and physical testing to find the actual failed part.",
            "Our technicians use professional scan tools plus old fashioned inspection. We road test, read live data, and verify the fault before quoting any repair. You pay for answers, not guesses, and we explain the findings in plain language.",
        ],
        "signs": [
            "Check engine, ABS, airbag or traction control light stays on",
            "Car hesitates, stalls, idles rough or lacks power",
            "Strange noises, smells or vibrations you cannot explain",
            "Fuel economy suddenly gets worse",
            "A warning message appears on the dash",
        ],
        "steps": [
            ("Scan and record", "We pull all stored and pending codes from every module, not just the engine computer, and record freeze frame data."),
            ("Live data and testing", "We watch sensors in real time and run targeted tests on the suspect circuits and components."),
            ("Physical inspection", "Wiring, connectors, vacuum lines and mechanical parts get a hands on check to confirm what the data suggests."),
            ("Clear report and quote", "You get a written explanation of the fault, the repair options, and an upfront price before any work begins."),
        ],
        "faqs": [
            ("Is the diagnostic fee applied to the repair?", "The diagnostic fee covers the technician time to find the fault. If you approve the repair with us, we apply the diagnostic fee toward the repair cost."),
            ("Can you diagnose any make or model?", "Yes. Our scan equipment covers domestic, Asian and European vehicles, and we service all makes and models."),
            ("My light went off by itself. Do I still need a check?", "Often yes. The code stays stored in memory even after the light turns off, and the underlying issue can return. A quick scan tells you whether it was a one time glitch or something developing."),
        ],
    },
    {
        "slug": "electrical-diagnostic",
        "name": "Electrical Diagnostic",
        "tagline": "From dead batteries to mystery drains, we trace it.",
        "img": "electrical.jpg",
        "card": "Wiring, sensors, modules and parasitic drain testing by technicians who read wiring diagrams for a living.",
        "intro": [
            "Electrical faults are the hardest problems to guess at. A light that flickers, a window that works sometimes, a battery that dies overnight, these are circuit problems that need systematic testing with meters and wiring diagrams, not parts swapping.",
            "We test voltage drops, check grounds, load test circuits and hunt parasitic drains with the car asleep. Because we diagnose down to the wire, you replace only what has actually failed.",
        ],
        "signs": [
            "Battery dies overnight or needs frequent boosts",
            "Lights dim, flicker, or some stop working",
            "Power windows, locks or seats work intermittently",
            "Blown fuses that keep blowing again",
            "Burning plastic smell or warm wiring",
        ],
        "steps": [
            ("Symptom mapping", "We reproduce the fault and map which circuits are involved using wiring diagrams for your exact vehicle."),
            ("Meter testing", "Voltage, resistance and voltage drop tests narrow the fault to a wire, connector, ground or component."),
            ("Drain testing", "For dead battery complaints we measure parasitic draw with the vehicle asleep and pull fuses to isolate the circuit."),
            ("Repair and verify", "We repair the wiring or replace the failed component, then retest the full circuit under load to prove the fix."),
        ],
        "faqs": [
            ("Why not just replace the battery first?", "A new battery masks a drain or charging fault for a few weeks, then dies too. Testing the charging system and parasitic draw first saves you buying parts you do not need."),
            ("Do you repair wiring or only replace parts?", "We do both. Many electrical faults are fixed with a proper wire repair, terminal replacement or ground cleaning, which costs far less than a new module."),
            ("Can you handle European car electronics?", "Yes. We work on all makes and models including European vehicles with complex module networks."),
        ],
    },
    {
        "slug": "fuel-filter-replacement",
        "name": "Fuel Filter Replacement",
        "tagline": "Clean fuel delivery for smooth, efficient running.",
        "img": "fuel-filter.jpg",
        "card": "Fuel filter replacement that protects injectors and restores proper fuel pressure.",
        "intro": [
            "The fuel filter catches rust, dirt and debris before they reach your injectors. When it clogs, fuel pressure drops and the engine starves under load, which feels like hesitation or power loss on hills and highway merges.",
            "We replace the filter with a quality unit, inspect the fuel lines and connections for leaks or corrosion, and confirm fuel pressure is back in spec before you drive away.",
        ],
        "signs": [
            "Engine hesitates or sputters under acceleration",
            "Hard starting, especially after sitting",
            "Loss of power going uphill or at highway speed",
            "Engine misfires or stalls at idle",
            "Fuel pump sounds louder than usual, straining against a clog",
        ],
        "steps": [
            ("Pressure relief", "We safely relieve fuel system pressure and disconnect the battery before opening any fuel connection."),
            ("Filter replacement", "The old filter comes out and a new quality filter goes in, with fresh seals and proper line connections."),
            ("Line inspection", "Fuel lines, clamps and fittings are inspected for rust, cracks and leaks while the system is open."),
            ("Pressure verification", "We restore pressure and confirm the system holds spec with no leaks before a final road test."),
        ],
        "faqs": [
            ("How often should the fuel filter be changed?", "Many manufacturers list it as a 40,000 to 60,000 km service, but driving with low quality fuel or an older tank can clog it sooner. If you feel hesitation, have it checked regardless of mileage."),
            ("Is it part of the fuel pump?", "On some newer cars the filter is inside the tank with the pump. On many others it is an inline filter under the car that we can service separately for much less than a pump job."),
            ("Will a new filter improve fuel economy?", "If the old filter was restricting flow, yes. The engine no longer has to work as hard to get the fuel it needs."),
        ],
    },
    {
        "slug": "preventative-maintenance",
        "name": "Preventative Maintenance",
        "tagline": "Small services now prevent big repairs later.",
        "img": "preventative-maintenance.jpg",
        "card": "Factory scheduled maintenance, fluid services and full vehicle inspections that keep you ahead of breakdowns.",
        "intro": [
            "Preventative maintenance is simply doing the right service at the right mileage. Fluids, filters, belts and wear parts all have a service life, and replacing them on schedule costs a fraction of repairing the damage when they fail.",
            "We follow your manufacturer maintenance schedule, not an upsell script. Every visit includes a written inspection report with photos of anything we find, prioritized by safety first, so you can plan instead of panic.",
        ],
        "signs": [
            "You are near a 30, 60, 90 or 120k service milestone",
            "It has been over a year since a full inspection",
            "You bought a used car and want a baseline health check",
            "A long road trip is coming up",
            "Fluids look dark or levels keep dropping",
        ],
        "steps": [
            ("Schedule review", "We check your manufacturer schedule against your mileage and service history to build the right service list."),
            ("Full inspection", "A bumper to bumper inspection covers brakes, suspension, steering, belts, hoses, fluids, lights, tires and battery."),
            ("Scheduled services", "We perform the due items: fluids, filters, spark plugs, coolant or transmission service as the schedule calls for."),
            ("Written report", "You get a clear report with priorities: what is safety critical now, what to plan for soon, and what is fine."),
        ],
        "faqs": [
            ("Do I have to service at the dealer to keep my warranty?", "No. In Canada you can have maintenance done at any qualified shop as long as the work meets manufacturer specs and you keep records. We document everything."),
            ("What does the inspection cover?", "Brakes, tires, suspension, steering, belts, hoses, all fluid levels and condition, battery, lights, wipers and exhaust. You get the results in writing."),
            ("How do I know you are not overselling?", "We show you. Worn parts are saved for your inspection, measurements like brake pad thickness are written down, and everything is prioritized so you decide what happens now and what waits."),
        ],
    },
    {
        "slug": "brake-replacement-repair",
        "name": "Brake Replacement and Repair",
        "tagline": "Stop shorter, drive safer, with complete brake service.",
        "img": "brake-service.jpg",
        "card": "Pads, rotors, calipers and full brake system repair with proper bedding and a road test on every job.",
        "intro": [
            "Brakes are your car most important safety system, and they wear a little every time you drive. Pads thin out, rotors develop grooves and rust, calipers can stick, and brake fluid absorbs moisture over time which lowers its boiling point.",
            "We service the complete system: pads, rotors, calipers, hoses, hardware and fluid. Every brake job is measured, machined or replaced to spec, then road tested and bedded so the pedal feels firm and stops are quiet from day one.",
        ],
        "signs": [
            "Squealing, squeaking or grinding when you brake",
            "Brake pedal feels soft, spongy or sinks low",
            "Car pulls to one side while braking",
            "Vibration or pulsing through the pedal or steering wheel",
            "Brake warning light is on, or stopping distances feel longer",
        ],
        "steps": [
            ("Measure everything", "Pad thickness, rotor thickness and runout, caliper slide movement and fluid condition are all measured and recorded."),
            ("Replace or machine", "Pads are replaced, rotors are machined or replaced to stay above minimum thickness, and sticking calipers are serviced or replaced."),
            ("Hardware and fluid", "New hardware, shims and lubricant where required, plus a brake fluid flush if the fluid is old or contaminated."),
            ("Bed and road test", "Pads are bedded to the rotors and the car is road tested to confirm a firm pedal, straight stops and no noise."),
        ],
        "faqs": [
            ("Do I need new rotors or can they be machined?", "If the rotor is thick enough and not cracked or severely rusted, machining restores a true surface for less money. We measure first and show you the numbers, then recommend whichever is right."),
            ("Why do my brakes squeak in the morning?", "Light surface rust forms overnight, especially in humid weather, and wipes off after a few stops. Constant squealing while driving usually means the wear indicators are touching and the pads are due."),
            ("How long do brake pads last?", "Typically 40,000 to 70,000 km depending on driving style, traffic and pad material. We measure pad thickness at every visit so you get a real answer for your car."),
        ],
    },
    {
        "slug": "engine-repair-maintenance",
        "name": "Engine Repair and Maintenance",
        "tagline": "From tune ups to major engine work, done properly.",
        "img": "engine-repair.jpg",
        "card": "Engine diagnostics, tune ups, gaskets, seals and mechanical repairs for all makes and models.",
        "intro": [
            "The engine is a system of systems: fuel, air, spark, cooling and lubrication all have to work together. When one falls behind you get warning lights, oil leaks, overheating, noise or lost power, and small faults become expensive fast if ignored.",
            "We handle the full range, from tune ups and gasket replacements to intake, cooling and internal mechanical repair. Every job starts with diagnosis, uses quality gaskets and parts, and ends with a road test and leak check.",
        ],
        "signs": [
            "Oil or coolant spots where you park",
            "Engine overheats or temperature gauge climbs",
            "Ticking, knocking or tapping noises from the engine",
            "Rough idle, misfires or loss of power",
            "Excessive exhaust smoke or strong fuel smell",
        ],
        "steps": [
            ("Diagnose first", "Compression, leak down, smoke testing and computer diagnostics pinpoint whether the fault is fuel, spark, air, cooling or mechanical."),
            ("Upfront quote", "You approve a clear written quote with parts and labour broken out before we disassemble anything."),
            ("Quality parts", "We use quality gaskets, seals and components torqued to manufacturer spec, with new fluids where the job requires."),
            ("Test and verify", "After assembly we pressure test, check for leaks, clear codes and road test to confirm the repair under real driving."),
        ],
        "faqs": [
            ("My engine leaks oil. Is that serious?", "It depends on the source and rate. A seeping valve cover gasket is common and affordable. A rear main seal leak is bigger work. We clean the area, add dye if needed, and show you exactly where it comes from."),
            ("What is a tune up today?", "Modern tune ups mean spark plugs, ignition components as needed, air and fuel filters, throttle body cleaning and a full scan. It restores efficiency the manufacturer designed in."),
            ("Do you do engine replacements?", "Yes. When repair costs exceed the value of a rebuild or replacement, we will tell you honestly and quote quality replacement options."),
        ],
    },
    {
        "slug": "coolant-flush",
        "name": "Coolant Flush",
        "tagline": "Protect against overheating and winter freeze ups.",
        "img": "coolant-flush.jpg",
        "card": "Complete cooling system flush with fresh antifreeze mixed for Canadian winters, plus pressure testing.",
        "intro": [
            "Coolant does two jobs: it carries heat away from the engine and it prevents freezing and corrosion inside the system. Old coolant turns acidic, loses its anti corrosion additives, and lets scale build up in the radiator and heater core.",
            "Our flush exchanges the old coolant for fresh antifreeze mixed to handle Ontario winters, and we pressure test the system to catch weak hoses, a tired radiator cap or a seeping water pump before they strand you.",
        ],
        "signs": [
            "Temperature gauge runs higher than normal",
            "Coolant looks rusty, brown or has particles floating in it",
            "Heater blows lukewarm in winter",
            "Sweet smell under the hood or low coolant level",
            "It has been more than 5 years or 100,000 km since a flush",
        ],
        "steps": [
            ("Inspect the system", "Hoses, clamps, radiator, reservoir and water pump are checked for leaks, swelling and corrosion."),
            ("Flush and exchange", "Old coolant is fully exchanged, not just drained, so acidic fluid does not stay trapped in the block and heater core."),
            ("Refill to spec", "Fresh antifreeze goes in, mixed for freeze protection well below minus 35, and the system is bled of air pockets."),
            ("Pressure test", "The system is pressure tested hot to verify it holds, and we confirm the heater blows hot and the gauge stays steady."),
        ],
        "faqs": [
            ("Can I just top up the coolant?", "Topping up fixes the level but not worn out coolant. If the fluid is old or rusty, a flush is the real fix. We test the coolant condition and tell you which one you need."),
            ("Why does my heater blow cold?", "Often low coolant, a stuck thermostat or a clogged heater core. We diagnose before flushing so you do not pay for a service that cannot fix it."),
            ("How often should coolant be flushed?", "Most vehicles call for 5 years or 100,000 to 160,000 km. Your owner manual has the exact interval for your coolant type."),
        ],
    },
    {
        "slug": "ball-joint-replacement",
        "name": "Ball Joint Replacement",
        "tagline": "Tight steering and safe handling start here.",
        "img": "ball-joint.jpg",
        "card": "Ball joint and control arm replacement with proper torque specs and a road test on every job.",
        "intro": [
            "Ball joints are the pivot points that connect your wheels to the suspension, letting the wheels steer and move up and down at the same time. They carry the weight of the car, so when they wear out you get looseness in the steering and, in extreme cases, a wheel that can separate.",
            "We replace worn ball joints with quality parts, torque every fastener to manufacturer spec, and road test to confirm tight, quiet steering. If the control arm bushings are worn too, we will show you and let you decide.",
        ],
        "signs": [
            "Clunking or knocking over bumps, especially when turning",
            "Steering feels loose or wanders on the highway",
            "Uneven or feathered tire wear on the front tires",
            "Vibration in the steering wheel",
            "A technician notes play in the joint during inspection",
        ],
        "steps": [
            ("Lift and load test", "With the car on the lift we check each joint for vertical and lateral play under load, the only reliable test."),
            ("Replace the joint", "The worn joint is pressed or unbolted out and a new quality joint is installed, or the full control arm if that is the better repair."),
            ("Torque to spec", "Every fastener is torqued to manufacturer specification with suspension loaded where required."),
            ("Road test", "We road test over bumps and through turns to confirm the clunk is gone and steering is tight."),
        ],
        "faqs": [
            ("Can I drive with a worn ball joint?", "A slightly worn joint should be replaced soon. A badly worn or separating joint is dangerous and can let the wheel fold under the car. If you hear loud clunking, get it checked right away."),
            ("Do both sides need replacement?", "Not always, but joints wear at similar rates. We inspect both sides and recommend based on actual play, not guesswork."),
            ("Will I need an alignment after?", "Ball joint replacement can change alignment angles, so we recommend a check afterward to protect your tires."),
        ],
    },
    {
        "slug": "fuel-pump-replacement",
        "name": "Fuel Pump Replacement",
        "tagline": "Reliable starts and steady fuel pressure, restored.",
        "img": "fuel-pump.jpg",
        "card": "Fuel pump diagnosis and replacement with fuel pressure testing before and after the job.",
        "intro": [
            "The fuel pump lives inside your gas tank and pushes fuel to the engine at high pressure. When it weakens, pressure drops and the engine starves, which shows up as long cranking, sputtering at speed, or a car that dies and will not restart until it cools down.",
            "We confirm pump failure with fuel pressure and electrical testing before replacing anything, because the same symptoms can come from a relay, filter or wiring. The new pump module is tested under load before the car leaves.",
        ],
        "signs": [
            "Engine cranks a long time before starting",
            "Car sputters or loses power at highway speed",
            "Engine dies and restarts only after cooling down",
            "Whining or humming from the rear fuel tank area",
            "No start with fuel in the tank and a healthy battery",
        ],
        "steps": [
            ("Prove it is the pump", "Fuel pressure is tested at the rail, and pump current and relay operation are checked electrically."),
            ("Safe replacement", "The tank is accessed safely, the module assembly is replaced with new seals, and the tank and lines are inspected."),
            ("Filter and strainer", "The pickup strainer is replaced and the system is checked for contaminated fuel that could kill a new pump."),
            ("Pressure verification", "Final pressure and volume tests confirm the new pump delivers full spec under load."),
        ],
        "faqs": [
            ("Why did my pump fail?", "Heat and low fuel level are the top killers. Fuel cools the pump, so habitually running near empty shortens its life. Contaminated fuel and old age are the other common causes."),
            ("Should I replace the whole module or just the pump?", "We usually recommend the complete module assembly. It includes the sender, strainer and seals, and it is far more reliable than swapping only the pump motor."),
            ("How long does the job take?", "Most fuel pump replacements take 2 to 4 hours depending on tank access. We will give you a firm time when you book."),
        ],
    },
    {
        "slug": "ac-service-replacement",
        "name": "AC Service and Replacement",
        "tagline": "Ice cold air for the hottest Toronto summer day.",
        "img": "ac-service.jpg",
        "card": "AC recharge, leak detection, compressor and component replacement with proper evacuation and testing.",
        "intro": [
            "Your air conditioning is a sealed system, so if it is low on refrigerant there is a leak somewhere. Simply topping it up without finding the leak means you will be back in a month, paying twice.",
            "We evacuate the system, find leaks with UV dye and electronic detectors, repair the failed component, then recharge with the exact refrigerant weight your car calls for. Vent temperatures are measured to prove it blows cold before you leave.",
        ],
        "signs": [
            "AC blows warm or only slightly cool",
            "Air gets cold then turns warm in traffic",
            "Clicking or grinding when the AC turns on",
            "Musty smell from the vents",
            "Visible refrigerant oil stains on AC lines or fittings",
        ],
        "steps": [
            ("Performance test", "We measure vent temperature, pressures and compressor operation to see what the system is doing now."),
            ("Leak detection", "UV dye and an electronic leak detector find the exact leak point, from O rings to condensers to evaporators."),
            ("Repair and evacuate", "The failed part is replaced, then the system is vacuumed to remove air and moisture that destroy compressors."),
            ("Recharge to spec", "Refrigerant is charged by weight to the factory specification and vent temperature is verified ice cold."),
        ],
        "faqs": [
            ("Why is a recharge alone not enough?", "Refrigerant does not get used up. Low charge means a leak, and moisture entering through the leak damages the compressor. Finding and fixing the leak is the real repair."),
            ("How long does AC service take?", "A straightforward recharge with leak check takes about an hour. Component replacement like a compressor or condenser usually takes half a day."),
            ("Do you service the heating side too?", "Yes. If your heat is weak in winter we diagnose thermostats, heater cores and blend doors as well."),
        ],
    },
    {
        "slug": "wheel-bearings-replacement",
        "name": "Wheel Bearings Replacement",
        "tagline": "Silence the roar and keep your wheels rolling true.",
        "img": "wheel-bearing.jpg",
        "card": "Wheel hub and bearing replacement that eliminates humming, grinding and play at the wheel.",
        "intro": [
            "Wheel bearings let your wheels spin freely while carrying the full weight of the car. When they wear, they roar, and the noise usually changes when you steer left or right. A badly worn bearing develops play that affects braking and handling.",
            "We confirm the noisy bearing on the lift and with a road test, replace the hub assembly with a quality part, torque the axle nut to exact spec, and verify the noise is gone on a final drive.",
        ],
        "signs": [
            "Humming or roaring that gets louder with speed",
            "Noise changes pitch when you steer left or right",
            "Grinding noise from one wheel",
            "ABS or traction light on with a wheel speed code",
            "Steering wheel vibration at highway speed",
        ],
        "steps": [
            ("Isolate the bearing", "Road test plus on lift stethoscope testing pinpoints which bearing is noisy, so we never replace the wrong side."),
            ("Replace the hub", "The hub assembly is replaced with a quality unit. Sealed modern bearings are not serviceable, replacement is the correct fix."),
            ("Torque to spec", "The axle nut is torqued to the exact manufacturer specification, which is critical for bearing life."),
            ("Verify quiet", "A final road test confirms the roar is gone and ABS sensors read correctly."),
        ],
        "faqs": [
            ("Which side is making the noise?", "That is the key question and we answer it with testing, not guessing. Noise that gets louder steering right usually points to the left bearing, and we confirm on the lift."),
            ("Can I drive on a noisy bearing?", "For a short time if the noise just started, but a failing bearing can overheat, damage the hub and affect braking. Get it checked promptly."),
            ("Do bearings need regular replacement?", "No, they are not a maintenance item. Quality bearings often last 130,000 to 200,000 km. Potholes and curb hits shorten their life."),
        ],
    },
    {
        "slug": "strut-assembly-replacement",
        "name": "Strut Assembly Replacement",
        "tagline": "Restore the smooth, controlled ride your car was built for.",
        "img": "strut-assembly.jpg",
        "card": "Strut and shock replacement, including complete quick strut assemblies, for safe handling and comfort.",
        "intro": [
            "Struts and shocks control how your wheels move over bumps. When they wear out, the car bounces, dives under braking, leans in turns and takes longer to stop. Tires also wear unevenly because the wheel hops instead of staying planted.",
            "We replace worn struts with quality assemblies, inspect mounts, boots and springs while apart, and road test to confirm the ride is controlled and quiet. Complete assemblies save labour and replace all the wear parts at once.",
        ],
        "signs": [
            "Car bounces more than once after a bump",
            "Nose dives when braking or squats on acceleration",
            "Excessive body lean in turns",
            "Cupped or uneven tire wear",
            "Knocking over bumps or a floaty highway feel",
        ],
        "steps": [
            ("Bounce and leak check", "We test each corner for damping and inspect struts for oil leaks, broken mounts and worn boots."),
            ("Replace assemblies", "Worn struts are replaced, often with complete assemblies that include new mounts, boots and springs."),
            ("Inspect related parts", "Control arm bushings, sway bar links and ball joints are checked while the suspension is apart."),
            ("Road test", "We verify controlled ride, no noise over bumps, and stable braking and turning."),
        ],
        "faqs": [
            ("Should I replace struts in pairs?", "Yes, always per axle. A new strut on one side with a worn one on the other gives uneven handling and braking."),
            ("What is a quick strut assembly?", "A complete unit with strut, spring, mount and boot preassembled. It replaces every wear part at once, installs faster, and restores factory ride height."),
            ("How long do struts last?", "Typically 80,000 to 130,000 km depending on roads. Toronto potholes are hard on them, so we check yours at every inspection."),
        ],
    },
    {
        "slug": "oxygen-sensor-replacement",
        "name": "Oxygen Sensor Replacement",
        "tagline": "Fix the check engine light and get your mileage back.",
        "img": "oxygen-sensor.jpg",
        "card": "O2 sensor diagnosis and replacement that restores fuel economy and clears emissions codes.",
        "intro": [
            "Oxygen sensors tell your engine computer how to mix fuel and air. When a sensor gets slow or fails, the computer guesses, which means worse fuel economy, rough running, failed emissions tests and a check engine light that will not stay off.",
            "We verify the sensor is truly the fault with live data, because wiring and exhaust leaks can set the same codes. The new sensor is installed with anti seize, torqued correctly, and the system is confirmed in closed loop on a road test.",
        ],
        "signs": [
            "Check engine light with an O2 sensor code",
            "Fuel economy drops noticeably",
            "Rough idle or hesitation",
            "Rotten egg smell from the exhaust",
            "Failed Drive Clean or emissions test",
        ],
        "steps": [
            ("Confirm with live data", "We watch sensor waveforms and fuel trims to prove the sensor is slow or dead, not a wiring or exhaust leak issue."),
            ("Replace the sensor", "The failed sensor is removed with the proper socket and a new quality sensor is installed to the correct torque."),
            ("Check the circuit", "Heater circuit, wiring and connectors are tested so the new sensor is not condemned by a bad wire."),
            ("Verify operation", "Codes are cleared and a road test confirms fuel trims return to normal and the light stays off."),
        ],
        "faqs": [
            ("Can I drive with a bad O2 sensor?", "Short term, yes, but fuel economy suffers and a rich mixture can overheat and destroy the catalytic converter, which costs far more than a sensor."),
            ("Why not just clear the code?", "Clearing the code does not fix the sensor. The computer will set it again, usually within a few drive cycles, and the underlying problem continues."),
            ("Upstream or downstream sensor?", "We test both. Upstream sensors control fuel mixture, downstream sensors monitor the converter. The data tells us which one failed."),
        ],
    },
    {
        "slug": "battery-alternator-starter",
        "name": "Battery, Alternator and Starter Check",
        "tagline": "Start every morning with confidence.",
        "img": "battery-check.jpg",
        "card": "Complete starting and charging system testing: battery, alternator, starter, cables and parasitic drains.",
        "intro": [
            "Starting and charging problems all feel the same: click, slow crank, or nothing. But the fix could be a battery, an alternator, a starter, a corroded cable or a parasitic drain, and each costs very differently.",
            "We test the whole system as a system. Battery load test, alternator output under load, starter draw, cable voltage drops and parasitic drain are all measured, so you replace exactly the failed part and nothing else.",
        ],
        "signs": [
            "Slow cranking, especially on cold mornings",
            "Clicking sound when you turn the key",
            "Battery warning light on the dash",
            "Lights dim at idle but brighten when you rev",
            "Needing a boost more than once",
        ],
        "steps": [
            ("Battery load test", "The battery is tested under real load, not just voltage, to see if it can actually deliver cranking amps."),
            ("Charging test", "Alternator output is measured at idle and under full electrical load to confirm it charges in all conditions."),
            ("Starter draw test", "Starter current draw is measured to catch a failing starter before it strands you."),
            ("Cables and drains", "Cable connections are cleaned and tested for voltage drop, and parasitic drain is checked if the battery keeps dying."),
        ],
        "faqs": [
            ("How long do car batteries last in Ontario?", "Typically 3 to 5 years. Our winters are brutal on batteries, so we recommend testing every fall once the battery is over 3 years old."),
            ("My car needed a boost. Do I need a new battery?", "Not necessarily. A boost can follow a drain from lights left on, a weak alternator or a dying battery. Testing tells us which one before you spend money."),
            ("Do you replace batteries on the spot?", "Yes. We stock common sizes and most battery replacements take about 30 minutes including terminal cleaning and a charging system retest."),
        ],
    },
    {
        "slug": "cv-axle-shaft-assembly",
        "name": "CV Axle and Shaft Assembly Replacement",
        "tagline": "End the clicking and get power to the wheels.",
        "img": "cv-axle.jpg",
        "card": "CV axle replacement for clicking on turns, torn boots and vibration under acceleration.",
        "intro": [
            "CV axles deliver engine power to your front wheels while letting them steer and move with the suspension. Their joints are packed in grease under rubber boots. When a boot tears, grease flies out, dirt gets in, and the joint starts clicking on turns.",
            "We replace the complete axle assembly with a quality unit, which is more reliable than rebooting a joint that has already run dry. New axle nuts are torqued to spec and the car is road tested through full lock turns.",
        ],
        "signs": [
            "Clicking or popping when turning sharply",
            "Grease splattered on the inside of the wheel or under the car",
            "Vibration under acceleration that smooths out when coasting",
            "Clunk when shifting into drive or reverse",
            "Torn or cracked CV boot spotted during inspection",
        ],
        "steps": [
            ("Confirm the axle", "Full lock turns and on lift inspection confirm the clicking axle and check boot condition on both sides."),
            ("Replace the assembly", "The complete axle is replaced with a quality unit, including new axle nut and fresh transmission seal where applicable."),
            ("Torque to spec", "The axle nut is torqued to the exact manufacturer specification, critical for bearing and joint life."),
            ("Road test", "Figure eights and highway runs confirm no clicking, no vibration and no leaks."),
        ],
        "faqs": [
            ("Can you just replace the torn boot?", "If caught immediately before dirt enters, sometimes. Once the joint has clicked or run dry, the damage is done and a complete axle is the reliable fix."),
            ("How urgent is a torn boot?", "It is a countdown. The joint can last weeks or months after the boot tears, but once it starts clicking, replacement is the only fix. Earlier is cheaper."),
            ("Do both axles need replacement?", "Only the failed one, but we inspect both boots at every visit so the other side never surprises you."),
        ],
    },
    {
        "slug": "ignition-coils-spark-plugs",
        "name": "Ignition Coils and Spark Plugs Replacement",
        "tagline": "Smooth idle, strong acceleration, better mileage.",
        "img": "spark-plugs.jpg",
        "card": "Spark plug and ignition coil service that cures misfires, rough idle and hesitation.",
        "intro": [
            "Spark plugs fire thousands of times per minute to ignite the fuel mixture, and ignition coils supply the high voltage they need. Worn plugs and weak coils cause misfires, which feel like stumbling, shake the engine, waste fuel and can damage the catalytic converter.",
            "We read misfire data to find the guilty cylinders, replace plugs with the correct type for your engine, and replace only the coils that test bad. The result is a smooth idle and the power your car was built with.",
        ],
        "signs": [
            "Engine misfires, stumbles or shakes at idle",
            "Flashing check engine light",
            "Hesitation or lack of power on acceleration",
            "Hard starting",
            "Fuel economy gets worse for no clear reason",
        ],
        "steps": [
            ("Find the misfire", "Misfire counters and live data identify exactly which cylinders are affected and whether it is spark, fuel or compression."),
            ("Replace plugs", "Plugs are replaced with the exact type and gap your manufacturer specifies, platinum or iridium where required."),
            ("Test coils", "Each coil is tested. Only failed coils are replaced, so you never pay for parts that still work."),
            ("Verify smooth", "Codes are cleared and a road test confirms no misfires, smooth idle and full power."),
        ],
        "faqs": [
            ("The check engine light is flashing. Can I keep driving?", "A flashing light means an active misfire that can overheat and destroy the catalytic converter within minutes. Drive gently to the nearest shop or call us right away."),
            ("Should I replace all coils or just the bad one?", "We replace failed coils and test the rest. If the car has high mileage and multiple coils are weak, we will show you the data and let you decide."),
            ("How often do spark plugs need replacement?", "Iridium and platinum plugs often last 100,000 to 160,000 km. Copper plugs much less. Your owner manual lists the interval for your engine."),
        ],
    },
    {
        "slug": "engine-transmission-mount",
        "name": "Engine and Transmission Mount Replacement",
        "tagline": "Stop the clunk and feel the smoothness again.",
        "img": "engine-mount.jpg",
        "card": "Motor and transmission mount replacement that eliminates clunks, vibration and harsh shifting feel.",
        "intro": [
            "Engine and transmission mounts hold your powertrain in place while absorbing its vibration. They are rubber and hydraulic components, and they crack, collapse and leak with age. Failed mounts let the engine rock, which you feel as clunks, vibration at idle and harsh shifts.",
            "We inspect all mounts, replace the failed ones with quality parts, and support the powertrain properly during the job. Afterwards the car idles smooth and shifts without the thump.",
        ],
        "signs": [
            "Clunk when shifting into drive or reverse",
            "Vibration at idle that smooths out when driving",
            "Engine visibly rocks when revved",
            "Thump on acceleration or deceleration",
            "Cracked, collapsed or leaking mounts found on inspection",
        ],
        "steps": [
            ("Inspect all mounts", "Every mount is checked for cracks, collapse, fluid leaks and excess movement with the engine loaded."),
            ("Support and replace", "The powertrain is properly supported while failed mounts are replaced with quality parts."),
            ("Torque to spec", "All fasteners are torqued to manufacturer specification with the drivetrain at normal ride height where required."),
            ("Verify smooth", "We confirm no clunk on gear engagement, smooth idle and no new vibrations on the road test."),
        ],
        "faqs": [
            ("Can bad mounts cause other damage?", "Yes. Excess engine movement stresses exhaust flex pipes, axles, hoses and wiring. Replacing mounts early prevents those secondary failures."),
            ("Why does my car vibrate only at idle?", "At idle the engine shakes most and worn mounts cannot absorb it. Once RPM rises the shaking smooths out. Classic mount symptom."),
            ("Do all mounts need replacement at once?", "We replace the failed ones and report the condition of the rest. Mounts often fail around the same age, so we will tell you honestly what can wait."),
        ],
    },
    {
        "slug": "collision-body-work",
        "name": "Collision Body Work",
        "tagline": "Accident damage repaired, panels straight, lines restored.",
        "img": "body-work.jpg",
        "card": "Collision body repair: dent removal, panel replacement and alignment that bring your car back to factory lines.",
        "intro": [
            "A collision bends more than metal. Panels shift, gaps go uneven, paint cracks, and hidden brackets break behind the bumper. Proper body work restores the structure and the appearance together, not just the part you can see.",
            "We assess the full extent of the damage, including what hides behind the panels, then repair or replace each panel and align every gap to factory spec. You get a written estimate before work starts and a car that looks right from every angle.",
        ],
        "signs": [
            "Dents, creases or cracked paint from an accident or parking hit",
            "Panels that no longer line up, with uneven gaps at doors, hood or trunk",
            "Bumper cover that is loose, cracked or hanging",
            "A door, hood or trunk that is hard to open or close",
            "Paint scratched down to metal or plastic after an impact",
        ],
        "steps": [
            ("Full damage assessment", "We inspect the visible damage and what hides behind it: brackets, reinforcements and mounting points."),
            ("Written estimate", "You get a clear written estimate with parts and labour broken out before any work begins."),
            ("Panel repair or replacement", "Dents are pulled and filled where repair is sound; panels too far gone are replaced with quality parts."),
            ("Align and finish", "Every panel is aligned to factory gaps, then primed and prepped for paint."),
            ("Final inspection", "We check panel gaps, operation of doors and latches, and finish quality in daylight before handover."),
        ],
        "faqs": [
            ("Do you work with insurance claims?", "We provide a detailed written estimate and photos you can share with your insurer. You approve the work and the final bill is documented line by line."),
            ("How long does body work take?", "A single panel repair is often a few days including paint. Larger collision repairs depend on parts availability. We give you a firm timeline with the estimate."),
            ("Will the repair be noticeable?", "Our goal is invisible. Panels are aligned to factory gaps and paint is blended into adjacent panels so the repair disappears."),
        ],
    },
    {
        "slug": "frame-straightening",
        "name": "Frame Straightening",
        "tagline": "Bent frame, measured and pulled back to factory spec.",
        "img": "frame-straightening.jpg",
        "card": "Computer-measured frame straightening that restores structural alignment after a collision.",
        "intro": [
            "The frame is the skeleton your car is built on. Even a moderate impact can shift it by millimetres, and millimetres matter: a bent frame causes pulling, uneven tire wear, and doors that never quite close right again.",
            "We anchor your car to a frame bench and use computerized measuring to compare every point against factory specifications, then hydraulic pulls bring it back. We re-measure after every pull and show you the before and after readings.",
        ],
        "signs": [
            "Car pulls to one side after an accident",
            "Uneven or rapid tire wear following a collision",
            "Doors, hood or trunk that do not align after impact",
            "Visible bending or wrinkling in frame rails or aprons",
            "Another shop told you the frame might be bent",
        ],
        "steps": [
            ("Computerized measurement", "Electronic measuring compares your frame against factory specs and maps exactly where it moved."),
            ("Anchoring", "The car is locked to the frame bench so pulls move only the damaged area."),
            ("Hydraulic straightening", "Controlled pulls bring each point back to specification, re-measured after every pull."),
            ("Verification", "Final measurements confirm the frame matches factory spec before body panels go back on."),
        ],
        "faqs": [
            ("Is a bent frame always repairable?", "Not always. If the measuring shows damage beyond safe repair limits, we will tell you honestly rather than take the job. Safety comes first."),
            ("How do I know the frame is truly straight?", "We show you the computerized before and after measurements against factory specifications. Numbers, not promises."),
            ("Does frame work affect alignment?", "Yes, which is why frame straightening comes before panel alignment and a final wheel alignment check."),
        ],
    },
    {
        "slug": "auto-painting",
        "name": "Auto Painting",
        "tagline": "Factory-match colour, sprayed in a controlled booth.",
        "img": "auto-painting.jpg",
        "card": "Professional auto painting: full resprays, panel painting and colour matching with a flawless finish.",
        "intro": [
            "Great paint is 90 percent preparation. Sanding, masking, priming and a dust-free booth decide whether a paint job looks factory or looks repainted. We do the slow prep work so the colour lays down flawless.",
            "We match your factory colour code and blend into adjacent panels so repairs disappear. Full resprays, single panels, bumpers and spot repairs are all sprayed in a controlled booth and finished to a deep gloss.",
        ],
        "signs": [
            "Clear coat peeling, fading or turning chalky",
            "Scratches or chips down to primer or bare metal",
            "Panels that do not match after a previous repair",
            "Rust spots breaking through the paint",
            "You want a full colour change or refresh",
        ],
        "steps": [
            ("Prep and sanding", "Panels are sanded smooth, dents filled, and the surface cleaned. This step decides the final quality."),
            ("Masking and priming", "Everything that is not painted gets masked, then primer seals the surface for adhesion."),
            ("Colour match", "Your factory colour code is mixed and spray tested, then blended into adjacent panels for an invisible repair."),
            ("Booth spray and cure", "Base coat and clear coat are sprayed in the booth, then cured and polished to a factory gloss."),
        ],
        "faqs": [
            ("Will the new paint match the old paint?", "We mix to your factory colour code and blend into neighbouring panels, which hides the transition even on aged paint. That is how invisible repairs are done."),
            ("How long does a paint job take?", "A single panel is typically a few days with prep and cure time. Full resprays take longer. Your estimate includes a firm timeline."),
            ("What affects the cost of painting?", "The amount of prep work, the number of panels, and the paint type. We break it all out in the written estimate so you see exactly where the money goes."),
        ],
    },
    {
        "slug": "towing-service",
        "name": "24/7 Towing Service",
        "tagline": "Stranded at 2 AM? We are already rolling.",
        "img": "towing.jpg",
        "card": "24/7 towing across North York and the GTA. One call and a truck is on its way, day or night.",
        "intro": [
            "Breakdowns do not keep office hours, so neither do we. Our towing service runs 24 hours a day, 7 days a week across North York, Toronto and the surrounding GTA. One call to (416) 661-6665 and a truck is dispatched.",
            "We tow accident vehicles, breakdowns and non-runners straight to our shop at Unit 41 & 42, 4544 Dufferin Street, where our technicians can start diagnosing immediately, or to any address you choose.",
        ],
        "signs": [
            "Car broke down and will not restart",
            "Accident damage that makes the car unsafe to drive",
            "Flat tire with no usable spare",
            "Overheating that forces you to stop",
            "Any situation where driving further would cause more damage",
        ],
        "steps": [
            ("Call (416) 661-6665", "Tell us where you are, what happened, and where you want the car to go."),
            ("Truck dispatched", "The nearest available truck heads to you. We confirm the pickup location by phone."),
            ("Safe loading", "Your car is loaded on a flatbed with proper tie-downs to prevent any transport damage."),
            ("Delivered", "We bring it to our shop for immediate diagnosis or to the address of your choice."),
        ],
        "faqs": [
            ("Do you really tow at night and on weekends?", "Yes. 24 hours a day, 7 days a week, including holidays. If your car is down, call (416) 661-6665 any time."),
            ("Which areas do you cover?", "North York, Toronto, and the surrounding GTA including Mississauga, Scarborough, Etobicoke, Vaughan and Markham."),
            ("Can you tow my car directly to your shop?", "Yes, and most customers do. It lands in our bays and our technicians can start the diagnosis right away."),
        ],
    },
]

TESTIMONIALS = [
    {
        "name": "Daniel R.",
        "area": "North York",
        "text": "Brought my SUV in for brakes after another shop quoted me a fortune. Apex measured everything, showed me the rotors, and did pads and machining for a fair price. Pedal feels brand new. These guys are honest.",
    },
    {
        "name": "Priya S.",
        "area": "Yorkdale area",
        "text": "My check engine light had been on for months and two shops just cleared the code. Apex actually diagnosed it, a bad oxygen sensor, and fixed it the same day. Fuel economy is back to normal. Finally a shop that finds the real problem.",
    },
    {
        "name": "Marcus T.",
        "area": "Downsview",
        "text": "AC died in the middle of July. They found the leak, showed me the dye, replaced the condenser and had me blowing ice cold by the afternoon. Fair price, no upsell, I will be back for all my maintenance.",
    },
    {
        "name": "Elena K.",
        "area": "North York",
        "text": "As someone who knows nothing about cars, I appreciated how they explained everything in plain words and gave me options. Oil change, inspection report with photos, and zero pressure. Rare these days.",
    },
    {
        "name": "James W.",
        "area": "Maple",
        "text": "My car would not start two mornings in a row. They tested the whole charging system instead of just selling me a battery, turned out to be the alternator. Started first try every morning since, even in minus 20.",
    },
    {
        "name": "Sofia M.",
        "area": "North York",
        "text": "Had my struts and wheel bearing done here. The clunking is gone, the humming is gone, and the car rides like it did when it was new. They road tested it with me before I paid. Professional from start to finish.",
    },
]

GLOBAL_FAQS = [
    {
        "q": "What is the best car servicing shop in North York?",
        "a": "Drivers across North York choose Apex Collision Center for honest car servicing: real diagnosis before any quote, written upfront pricing, quality parts, and every repair road tested. Visit us at 4544 Dufferin Street, call (416) 661-6665, or book online. We service all makes and models, Monday to Saturday.",
    },
    {
        "q": "Where is Apex Collision Center located?",
        "a": "We are at 4544 Dufferin Street in North York, Ontario, M3H 5X2, easy to reach from the 401 and Finch Avenue. Free parking is available right at the shop.",
    },
    {
        "q": "What are your hours?",
        "a": "We are open Monday to Friday from 9:00 AM to 5:00 PM and Saturday from 10:00 AM to 3:00 PM. We are closed on Sundays.",
    },
    {
        "q": "Do I need an appointment or can I walk in?",
        "a": "Walk ins are welcome for inspections, diagnostics and quick services like oil changes and battery checks. For bigger repairs we recommend booking ahead so we can have the parts and a lift ready for you. Call (416) 661-6665 or use the booking form.",
    },
    {
        "q": "Do you work on all makes and models?",
        "a": "Yes. We service domestic, Asian and European vehicles of all makes and models, from compact cars to SUVs and light trucks.",
    },
    {
        "q": "How do your quotes work?",
        "a": "Every repair starts with diagnosis and a written quote with parts and labour broken out. We explain the findings in plain language and nothing gets done without your approval first.",
    },
    {
        "q": "Do you use quality parts?",
        "a": "Yes. We install quality parts that meet or exceed manufacturer specifications, and we will always tell you what is going on your car before we install it.",
    },
    {
        "q": "Can I wait while my car is serviced?",
        "a": "Absolutely. Our waiting area is comfortable, and most maintenance services like oil changes, battery checks and inspections are done within the hour.",
    },
    {
        "q": "How do I book a service?",
        "a": "Call or text (416) 661-6665, email mustafa@apexcollisioncenter.ca, or fill out the booking form on our contact page. Tell us your vehicle and what it needs and we will confirm your time.",
    },
]

# Service area pages: nearby cities whose drivers use the North York shop.
# Drive times are typical off-peak estimates via the 400-series highways.
AREAS = [
    {
        "slug": "north-york",
        "city": "North York",
        "title": "Auto Repair North York | Apex Collision Center",
        "h1": "Your North York neighbourhood repair shop",
        "drive": "right here in North York, at Unit 41 & 42, 4544 Dufferin Street",
        "intro": [
            "Apex Collision Center is a North York auto repair shop through and through. Our bays are at Unit 41 & 42, 4544 Dufferin Street in the York University Heights neighbourhood, right off Highway 401 and close to Finch Avenue, with free parking at the door and a comfortable waiting area inside.",
            "North York drivers use us for everything from oil changes and brake service to computer diagnostics, AC repair, suspension work and collision body repair. Walk ins are welcome for inspections, diagnostics, oil changes and battery checks. Larger repairs go on the schedule so the parts and a lift are ready when you arrive.",
        ],
        "landmarks": "On Dufferin Street between Finch Avenue and Sheppard Avenue, minutes from Highway 401, Yorkdale and the Allen Expressway.",
        "faqs": [
            ("Where exactly is Apex Collision Center?", "We are at Unit 41 & 42, 4544 Dufferin Street, Toronto, ON M3H 5X2, in the York University Heights area of North York. We are right off Highway 401 and close to Finch Avenue, with free parking on site."),
            ("Do I need an appointment?", "Walk ins are welcome for inspections, diagnostics, oil changes and battery checks. For larger repairs, booking ahead at (416) 661-6665 means the parts and a lift are ready when you arrive."),
            ("What are your hours?", "Monday to Friday 9:00 AM to 5:00 PM and Saturday 10:00 AM to 3:00 PM. Closed Sunday. Towing runs 24/7 across North York and the GTA."),
        ],
    },
    {
        "slug": "toronto",
        "city": "Toronto",
        "title": "Auto Repair Toronto | Apex Collision Center",
        "h1": "Auto repair Toronto drivers trust",
        "drive": "about 20 to 25 minutes from downtown via Allen Road and Highway 401",
        "intro": [
            "Drivers from across Toronto bring their cars to Apex Collision Center because honest diagnosis is worth a short drive. Our North York shop sits right off Highway 401 on Dufferin Street, about 20 to 25 minutes from downtown Toronto outside rush hour, with free parking at the door.",
            "Whether you need a routine oil change, brake service, computer diagnostics or major engine work, you get the same treatment every Toronto customer gets: a real diagnosis first, a written upfront quote, quality parts, and a road test before the car leaves.",
        ],
        "landmarks": "Easy to reach from the Allen Expressway, Yorkdale, Downsview, the 401 and Finch Avenue.",
        "faqs": [
            ("Do you serve customers from downtown Toronto?", "Yes. Many of our customers drive in from downtown, midtown and the east end. The shop is right off Highway 401 at Dufferin Street with free parking, and most maintenance visits take under an hour."),
            ("Is it worth driving from Toronto to North York for car service?", "Our customers say yes: upfront written quotes, diagnosis before parts are replaced, and no upsell pressure. For bigger repairs the savings and peace of mind easily cover a 20 minute drive."),
            ("Can I wait while my car is serviced?", "Absolutely. Our waiting area is comfortable and most maintenance like oil changes, battery checks and inspections finishes within the hour."),
        ],
    },
    {
        "slug": "mississauga",
        "city": "Mississauga",
        "title": "Auto Repair Mississauga | Apex Collision Center",
        "h1": "The Mississauga driver alternative to guesswork repairs",
        "drive": "about 20 to 30 minutes via Highway 401 east or Highway 427 north",
        "intro": [
            "Mississauga drivers who are tired of vague quotes and surprise charges make the straight run up Highway 401 or 427 to our North York shop. Apex Collision Center is about 20 to 30 minutes from most of Mississauga, right off the 401 at Dufferin Street.",
            "From oil changes and brakes to electrical diagnostics and AC repair, every job starts with testing, not guessing. You approve a written price before any work begins, and every repair is road tested before you drive back to Mississauga.",
        ],
        "landmarks": "Straight up Highway 401 east to Dufferin Street, or Highway 427 north to the 401. Free parking at the shop.",
        "faqs": [
            ("How far is Apex Collision Center from Mississauga?", "Typically about 20 to 30 minutes via Highway 401 east to Dufferin Street, depending on where in Mississauga you start and traffic."),
            ("Do you offer the same services to Mississauga customers?", "Yes. All 22 of our services, from preventative maintenance to engine repair, are available to every customer regardless of where they drive from."),
            ("Can I book a Saturday appointment from Mississauga?", "Yes. We are open Saturdays 10:00 AM to 3:00 PM, which suits drivers coming from Mississauga who cannot make it on a weekday."),
        ],
    },
    {
        "slug": "scarborough",
        "city": "Scarborough",
        "title": "Auto Repair Scarborough | Apex Collision Center",
        "h1": "Scarborough drivers welcome in North York",
        "drive": "about 25 to 35 minutes via Highway 401 west",
        "intro": [
            "From Scarborough it is one straight highway: Highway 401 west to Dufferin Street, about 25 to 35 minutes to our North York shop. Scarborough drivers come to us for the same reason everyone does, a shop that diagnoses before it quotes.",
            "All makes and models are welcome, from daily commuters to family SUVs. Book ahead for bigger repairs so parts and a lift are ready when you arrive, and most maintenance is done within the hour.",
        ],
        "landmarks": "Highway 401 west to Dufferin Street north. Minutes from Yorkdale and the Allen Expressway.",
        "faqs": [
            ("How do I get to you from Scarborough?", "Take Highway 401 west to Dufferin Street, then a short drive north to 4544 Dufferin Street. The trip is typically 25 to 35 minutes."),
            ("Do you work on all makes and models?", "Yes. Domestic, Asian and European vehicles, cars, SUVs and light trucks."),
            ("Should I book ahead driving from Scarborough?", "For diagnostics, oil changes and inspections you can walk in. For larger repairs, booking ahead means parts are ready and your car goes straight on the lift."),
        ],
    },
    {
        "slug": "etobicoke",
        "city": "Etobicoke",
        "title": "Auto Repair Etobicoke | Apex Collision Center",
        "h1": "Etobicoke car servicing minutes away",
        "drive": "about 15 to 20 minutes via Highway 401 east or Highway 427",
        "intro": [
            "Etobicoke is one of our closest service areas: about 15 to 20 minutes via Highway 401 east or Highway 427 to Dufferin Street in North York. Close enough for an oil change on a lunch break, and worth it for honest major repairs.",
            "Etobicoke drivers get the full Apex treatment: computer diagnostics before any quote, written upfront pricing, quality parts, and a road test on every job. All 22 services under one roof.",
        ],
        "landmarks": "Highway 401 east to Dufferin Street, or Highway 427 north to the 401. Free parking right at the shop.",
        "faqs": [
            ("How close are you to Etobicoke?", "About 15 to 20 minutes from most of Etobicoke via Highway 401 east to Dufferin Street."),
            ("Do you do same day service?", "For maintenance and diagnostics, usually yes. Call (416) 661-6665 in the morning and we will tell you honestly what fits that day."),
            ("What does a diagnostic cost?", "The diagnostic fee covers the technician time to find the actual fault, and it is applied toward the repair when you approve the work with us."),
        ],
    },
    {
        "slug": "vaughan",
        "city": "Vaughan",
        "title": "Auto Repair Vaughan | Apex Collision Center",
        "h1": "Vaughan car care straight down Dufferin",
        "drive": "about 15 to 20 minutes south on Dufferin Street or via Highway 400",
        "intro": [
            "Vaughan drivers have the simplest route of all: straight south on Dufferin Street to 4544 Dufferin in North York, typically 15 to 20 minutes. No highway maze, no confusion.",
            "Whether it is brakes before winter, AC before summer, or a check engine light that will not quit, you will get a clear diagnosis, a written quote, and work verified on the road before you head back up Dufferin.",
        ],
        "landmarks": "Dufferin Street runs straight from Vaughan to our door. Also easy via Highway 400 south to Finch or the 401.",
        "faqs": [
            ("Is there a direct route from Vaughan?", "Yes. Dufferin Street runs directly from Vaughan to our shop at 4544 Dufferin Street in North York, about 15 to 20 minutes."),
            ("Do you service European cars?", "Yes. We service domestic, Asian and European vehicles of all makes and models."),
            ("Can I get a quote before driving down?", "Call or email with your vehicle details and symptoms and we will give you an honest estimate range, confirmed with a written quote after diagnosis."),
        ],
    },
    {
        "slug": "markham",
        "city": "Markham",
        "title": "Auto Repair Markham | Apex Collision Center",
        "h1": "Markham drivers, one highway away",
        "drive": "about 20 to 30 minutes via Highway 404 south to Highway 401 west",
        "intro": [
            "From Markham it is Highway 404 south to the 401 west, then off at Dufferin Street: typically 20 to 30 minutes to our North York shop. Markham drivers come for major work where an honest second opinion saves real money.",
            "Engine diagnostics, suspension, electrical faults and AC repair are our most requested services from Markham customers. Every one starts with testing and a written upfront quote you approve first.",
        ],
        "landmarks": "Highway 404 south to Highway 401 west, exit at Dufferin Street. Free parking at the shop.",
        "faqs": [
            ("How long is the drive from Markham?", "Typically 20 to 30 minutes via Highway 404 south to Highway 401 west, exiting at Dufferin Street."),
            ("Do you give second opinions on other shops quotes?", "Yes, and Markham drivers ask us often. Bring the quote or the diagnosis and we will verify it with our own testing and give you a straight answer."),
            ("Do I need an appointment?", "Walk ins are welcome for inspections and quick services. For bigger jobs, booking ahead guarantees parts and a lift are ready."),
        ],
    },
]

# Homepage extended FAQ. Visible text and JSON-LD must stay word for word identical.
HOME_FAQS = [
    ("How much does a brake job cost in North York?", "Brake cost depends on the vehicle, the condition of the pads and rotors, and whether the calipers need service. Apex Collision Center diagnoses first, then gives you a written quote with parts and labour broken out before any work starts. Call (416) 661-6665 with your year, make and model for a firm number."),
    ("Do I need an appointment for an oil change in North York?", "Walk-ins are welcome for oil changes at Apex Collision Center on Dufferin Street, but a quick call to (416) 661-6665 saves waiting. Saturdays are busiest, so booking ahead helps."),
    ("What should I do when my check engine light comes on?", "If the light is steady, book a diagnostic as soon as practical. If it is flashing, reduce speed and stop driving because a flashing light usually means a misfire that can damage the catalytic converter. Apex Collision Center scans the codes and tests the circuit before replacing anything."),
    ("Do you service all makes and models?", "Yes. Apex Collision Center services and repairs all makes and models, including domestic, Asian and European vehicles, at our North York shop on Dufferin Street."),
    ("Where are you located and is there parking?", "Apex Collision Center is at Unit 41 & 42, 4544 Dufferin Street, Toronto (York University Heights, North York), ON M3H 5X2, close to Finch Avenue and Highway 401. Free parking is available on site."),
    ("What are your hours?", "Apex Collision Center is open Monday to Friday from 9:00 AM to 5:00 PM and Saturday from 10:00 AM to 3:00 PM. We are closed Sunday. Towing runs 24/7."),
    ("Do you offer a written quote before starting work?", "Yes. Every repair at Apex Collision Center starts with testing and a written quote that lists parts and labour separately. Nothing begins until you approve the price."),
    ("How do I know you diagnosed the right problem?", "We scan the computer, test the circuit by hand and confirm the failure before quoting. We save the worn parts for your inspection, give you the measurements, and road test every repair before you pay."),
    ("Do you do AC service in the summer?", "Yes. Apex Collision Center recharges AC systems, finds leaks, and replaces compressors and components with proper evacuation and testing. Book ahead in June and July."),
    ("My car pulls to one side. What causes that?", "Pulling can come from tire pressure, an alignment issue, a dragging brake caliper, or worn suspension parts like ball joints and control arm bushings. Apex Collision Center tests each possibility before recommending a repair."),
    ("How often should I change my oil in Ontario?", "Follow the interval in your owner's manual. For most modern vehicles on full synthetic oil that is roughly every 8,000 to 12,000 kilometres or once a year, whichever comes first. Short city trips and cold Ontario starts shorten that."),
    ("Do you offer Saturday appointments?", "Yes. Apex Collision Center is open Saturday from 10:00 AM to 3:00 PM. Call (416) 661-6665 to reserve a spot, especially for a repair that needs a lift."),
    ("Can you do a pre-purchase inspection?", "Yes. A pre-purchase inspection at Apex Collision Center covers the engine, transmission, brakes, suspension, tires, fluids, electronics and a road test, with a written summary of what we found. Call (416) 661-6665 to book."),
    ("Do you sell tires or do alignments?", "Tire sales and alignments are handled by our partner shops. Apex Collision Center focuses on mechanical repair, diagnostics, brakes, suspension, AC and maintenance. Call (416) 661-6665 and we will point you to a trusted partner."),
    ("How do I book a repair?", "Call (416) 661-6665 or book online at apexcollisioncenter.ca/contact.html. Tell us your vehicle, the symptom and when it happens, and we will find a time and a bay."),
    ("Do you work on hybrid and electric vehicles?", "Apex Collision Center services brakes, suspension, tires and general maintenance on most hybrids. High-voltage battery and drive unit work is referred to a specialist. Call (416) 661-6665 with your model to confirm."),
]

AREAS.append(
    {
        "slug": "downtown-toronto",
        "city": "Downtown Toronto",
        "title": "Downtown Toronto Auto Repair | Apex Collision Center",
        "h1": "Car servicing for Downtown Toronto drivers",
        "drive": "about 25 to 45 minutes via Allen Road north to Highway 401, then Dufferin Street",
        "intro": [
            "Apex Collision Center is a North York auto repair shop at Unit 41 & 42, 4544 Dufferin Street, reached from Downtown Toronto by Allen Road north to Highway 401 and then Dufferin Street. We diagnose before we quote, give you a written price, and road test every repair. We are open Saturdays, 10:00 AM to 3:00 PM.",
        ],
        "landmarks": "Allen Road north to Highway 401, then Dufferin Street. Close to Finch Avenue, with free parking at the shop.",
        "faqs": [
            ("How far is Apex Collision Center from Downtown Toronto?", "Most drivers take Allen Road north to Highway 401 and then Dufferin Street. Allow roughly 25 to 45 minutes depending on traffic and where downtown you start. Saturday mornings are usually the easiest run."),
            ("Do you take Saturday appointments for Downtown Toronto drivers?", "Yes. We are open Saturday from 10:00 AM to 3:00 PM, and Monday to Friday from 9:00 AM to 5:00 PM. Call (416) 661-6665 to reserve a time, especially for repairs that need a lift."),
            ("My car barely gets driven. Does it still need servicing?", "Yes. Oil, brake fluid and tires age with time as well as distance, and short trips and long sits are hard on batteries. A low-mileage car should still get an annual inspection and an oil change on the schedule in its owner's manual."),
            ("What should I bring to my appointment?", "Bring the vehicle, any warning-light or noise details you can describe, and your service history if you have it. Tell us when the problem happens, such as cold starts, braking or turning, because that shortens diagnosis."),
        ],
    }
)
